#!/usr/bin/env python3
"""Temporary helper for the 2026-09-05 Deed ornament replacement audit closure."""

from __future__ import annotations

import json
from pathlib import Path

MANIFEST = Path('.github/asset-provenance-remediation.json')
AUDIT = Path('docs/ASSET_PROVENANCE_AUDIT.md')
BATCH_ID = 'deed-ornament-replacement-2026-09-05'
IDENTITY_COMMIT = 'bdcd916a0105fe32b7117a27ffe899cfe0e6e1e6'


def update_manifest() -> None:
    data = json.loads(MANIFEST.read_text(encoding='utf-8'))
    batches = data.get('batches')
    if data.get('version') != 2 or not isinstance(batches, list):
        raise SystemExit('expected version 2 remediation manifest')
    if any(batch.get('id') == BATCH_ID for batch in batches):
        return

    batches.append({
        'id': BATCH_ID,
        'description': (
            'Replacement Deed ornamental divider, manually created in Illustrator from '
            'OpenAI-generated source artwork after retiring the prior externally traced ornament.'
        ),
        'defaults': {
            'origin': 'project-created',
            'creator': 'Tymon Scott / Gauntlet project, using OpenAI-generated source imagery',
            'source': (
                'Direct project-owner attestation on 2026-09-05: the replacement '
                'card-design/deed-ornamental-divider.svg was created manually in Adobe Illustrator '
                "from an ornament image generated by OpenAI/ChatGPT under Tymon Scott's direction. "
                'This replacement supersedes the prior divider that had been traced from an '
                'externally found ornament. The replacement SVG also contains Adobe XMP/C2PA '
                'provenance metadata from the Illustrator export.'
            ),
            'rights': (
                "Project-created final vector artwork. The generated source stage is covered by "
                "OpenAI Terms of Use, which assign to the user OpenAI's right, title, and interest, "
                'if any, in Output to the extent permitted by applicable law '
                '(https://openai.com/policies/terms-of-use/). Manual Illustrator construction/editing '
                'is project-authored. This record does not assert copyrightability, uniqueness, or '
                'absence of third-party rights.'
            ),
            'notes': (
                'The prior external-source traced ornament is no longer present in the current '
                'governed asset. This record applies only to the replacement binary introduced at '
                'the documented identity checkpoint.'
            ),
        },
        'evidence_basis': {
            'user_attestation': (
                'Gauntlet project conversation, 2026-09-05: project owner supplied ornament.svg '
                'and stated that it was created in Illustrator from the OpenAI-generated ornament image.'
            ),
            'identity_commit': IDENTITY_COMMIT,
            'rights_reference': 'https://openai.com/policies/terms-of-use/',
            'embedded_metadata': 'Adobe XMP/C2PA provenance metadata in the replacement SVG.',
        },
        'assets': [{'path': 'card-design/deed-ornamental-divider.svg'}],
    })
    MANIFEST.write_text(json.dumps(data, indent=2, ensure_ascii=False) + '\n', encoding='utf-8')


def update_audit() -> None:
    text = AUDIT.read_text(encoding='utf-8')
    text = text.replace(
        '**Status:** Active legacy-remediation record  ',
        '**Status:** Complete for current governed asset corpus  ',
    )
    text = text.replace(
        'The explicit provenance ledger now contains **367 records** for **368 current governed files**.',
        'The explicit provenance ledger now contains **368 records** for **368 current governed files**.',
    )

    batch = f'''### Batch 22 — replacement Deed ornamental divider

**Status:** Resolved  
**Assets:** 1

`card-design/deed-ornamental-divider.svg` was replaced on 2026-09-05 with new project-created vector artwork. The project owner supplied the replacement and directly attested that it was created manually in Adobe Illustrator from an ornament image generated by OpenAI/ChatGPT under Tymon Scott's direction. The prior divider that had been traced from an externally found ornament is no longer present in the current governed corpus.

The replacement binary was first committed at `{IDENTITY_COMMIT}`, which serves as its exact identity checkpoint. The SVG also contains Adobe XMP/C2PA provenance metadata from the Illustrator export. The final asset is recorded as `project-created`, with the generated source stage and manual Illustrator construction documented separately in its source and rights fields.

'''
    if '### Batch 22 — replacement Deed ornamental divider' not in text:
        marker = '## Controls applied\n'
        if marker not in text:
            raise SystemExit('audit controls marker not found')
        text = text.replace(marker, batch + marker, 1)

    current = '''## Current governed-asset status

A fresh full-history inventory after replacing and materializing the Deed divider finds:

- **368 current governed files**;
- **368 explicit provenance records**;
- **0 current `legacy-unresolved` files**;
- **0 unrecorded post-baseline anomalies**.

The former external-source exception, `card-design/deed-ornamental-divider.svg`, has been retired and replaced by the project-created Illustrator/OpenAI-derived ornament documented in Batch 22. There are therefore no unresolved assets in the current governed `images/` and `card-design/` corpus as of this audit state.

This closes the current legacy-remediation backlog. The governance policy and CI remain active so any new or modified governed asset must continue to carry explicit origin, creator, source, rights basis, and SHA-256 provenance before it can merge.
'''
    marker = '## Remaining legacy backlog\n'
    if marker in text:
        text = text.split(marker, 1)[0].rstrip() + '\n\n' + current
    elif '## Current governed-asset status' not in text:
        text = text.rstrip() + '\n\n' + current

    AUDIT.write_text(text, encoding='utf-8')


if __name__ == '__main__':
    update_manifest()
    update_audit()
