(() => {
  const CANONICAL_SOURCE = '/artifacts/v0.6.3/release-candidate/Gauntlet_v0.6.3_Canonical_Data.json';
  const FACTIONS = [['neutral','Neutral'],['military','Military'],['diplomats','Diplomats'],['financiers','Financiers'],['intelligence','Intelligence'],['mystics','Mystics'],['inquisition','Inquisition']];
  const LEADERS = [
    {faction:'military',factionLabel:'Military',name:'General',image:'../images/general.png',note:'Movement and attack',sections:[['Command','Maximum 2. The first time each turn you win a battle, gain 1 Command.'],['Onward','During your Movement, before a pending battle is created, move one additional Position. This movement may create a pending battle.','1 Command'],['Rally','Before dice are rolled in a battle you initiated, add +1 to your battle total.','1 Command'],['Rout','At the end of the Aftermath of a battle you initiated and won, advance one Position. This movement may create a pending battle.','2 Command']]},
    {faction:'military',factionLabel:'Military',name:'Commandant',image:'../images/commandant.png',note:'Defense and control',sections:[['Command','Maximum 2. The first time each turn you win a battle, gain 1 Command.'],['Hold','After you become the defender in a battle on a Territory you control, gain Defensive Edge for that battle. If you already have Defensive Edge, add +1 to your battle total instead.','1 Command'],['Stand Firm','In the Aftermath after you lose as defender, reduce the retreat by one Position. Minimum zero.','1 Command'],['Counteroffensive','During your Movement, if you won a battle as defender earlier this turn, move one additional Position. This movement may create a pending battle.','2 Command']]},
    {faction:'diplomats',factionLabel:'Diplomats',name:'Ambassador',image:'../images/ambassador.png',note:'Agreement and card flow',sections:[['Influence','Begin with 1 Influence and build toward a maximum of 10.'],['Cordiality','Once per turn, after the opponent accepts your Terms, draw one card.'],['Peace Treaty','At the start of your turn, after Capture, five different ratified Proposals win the game.']]},
    {faction:'diplomats',factionLabel:'Diplomats',name:'Senator',image:'../images/senator.png',note:'Risk management and resilience',sections:[['Influence','Begin with 1 Influence and build toward a maximum of 10.'],['Political Capital','Once per turn, sacrifice cards from Hand to recover an equal amount of Influence that would otherwise be lost after refused Terms.'],['Peace Treaty','At the start of your turn, after Capture, five different ratified Proposals win the game.']]},
    {faction:'financiers',factionLabel:'Financiers',name:'Banker',image:'../images/banker.png',note:'Collateral and flexible financing',sections:[['Capital','Begin with 2 Capital. Cards in Treasury raise the amount of Capital you can retain.'],['Line of Credit','On the first Deed purchase of your turn, one card may contribute part of the price as collateral; pay the remainder with Capital.'],['Controlling Interest','Own the Deed to every Territory currently in the Gauntlet and win immediately.']]},
    {faction:'financiers',factionLabel:'Financiers',name:'Executive',image:'../images/executive.png',note:'Offensive acquisition and control',sections:[['Capital','Begin with 2 Capital. Cards in Treasury raise the amount of Capital you can retain.'],['Hostile Takeover','During Denouement, after winning as attacker and becoming the occupier of an enemy Territory, take the Faction Action to buy or buy out its Deed. A successful purchase advances your Front Line by one Territory, if able; it never creates isolated control.'],['Controlling Interest','Own the Deed to every Territory currently in the Gauntlet and win immediately.']]},
    {faction:'intelligence',factionLabel:'Intelligence',name:'Ranger',image:'../images/ranger.png',note:'Terrain and field operations',sections:[['Missions',"Completed normal Missions grant 1 Operation Progress and Intel equal to the card's value."],['Fieldcraft',"Once per turn, spend 1 Intel to ignore a Territory's printed effect when it would affect you, your movement, or a battle involving you.",'1 Intel'],['Special Operation','When Operation Progress exceeds opposing controlled Territories, prepare and complete a Special Operation to win.']]},
    {faction:'intelligence',factionLabel:'Intelligence',name:'Spymaster',image:'../images/spymaster.png',note:'Mission tempo and coordination',sections:[['Missions',"Completed normal Missions grant 1 Operation Progress and Intel equal to the card's value."],['Mission Control','Once per turn, after completing a normal Mission, immediately start another eligible Mission from Hand without spending an Action. It cannot complete that turn and cannot be a Special Operation.'],['Special Operation','When Operation Progress exceeds opposing controlled Territories, prepare and complete a Special Operation to win.']]},
    {faction:'mystics',factionLabel:'Mystics',name:'Alchemist',image:'../images/alchemist.png',note:'Sacrifice sequencing and conversion',sections:[['Rites','The first completed Rite unlocks Invocation; the second unlocks Transmutation; the third unlocks Convergence and the Ritual of Ascendance.'],['Materia Prima','The first qualifying sacrifice from Hand on your turn draws one replacement card; during battle, draw after the battle resolves.'],['Ascendance','Complete all three Rites, then complete the Ritual of Ascendance to win.']]},
    {faction:'mystics',factionLabel:'Mystics',name:'Spirit Walker',image:'../images/spirit walker.png',note:'Ritual endurance and protection',sections:[['Rites','The first completed Rite unlocks Invocation; the second unlocks Transmutation; the third unlocks Convergence and the Ritual of Ascendance.'],['Guardians of the Circle','The first time on your turn a battle loss would interrupt a begun Rite or Ritual, put an Arcane card from Hand in your Graveyard of the required value to prevent that interruption.'],['Ascendance','Complete all three Rites, then complete the Ritual of Ascendance to win.']]},
    {faction:'inquisition',factionLabel:'Inquisition',name:'Grand Inquisitor',image:'../images/grand inquisitor.png',note:'Judgment and efficient Purges',sections:[['Conviction','Gain Conviction from qualifying opposing post-battle Graveyard entries, up to 4.'],['Final Judgment','Once per turn during the Aftermath of a battle you won, after battle cards are cleared, immediately Purge without spending an Action and reduce its Conviction cost by 1, minimum 1.'],['Purification',"If the opponent's normal Draw produces nothing because both Draw Pile and Discard Pile are empty, win immediately."]]},
    {faction:'inquisition',factionLabel:'Inquisition',name:'Witch Hunter',image:'../images/witch hunter.png',note:'Defense, retaliation, and pursuit',sections:[['Conviction','Gain Conviction from qualifying opposing post-battle Graveyard entries, up to 4.'],['Relentless Pursuit','Once per turn, at the end of the Aftermath of a battle an opponent initiated against you and lost, spend 2 Conviction to end their turn and advance one Position toward their end. Any resulting pending battle uses you as attacker.','2 Conviction'],['Purification',"If the opponent's normal Draw produces nothing because both Draw Pile and Discard Pile are empty, win immediately."]]}
  ];
  const slugify = value => String(value ?? '').toLowerCase().normalize('NFKD').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
  const esc = value => String(value ?? '').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'})[c]);
  function leaderCard(l){const extra=l.name==='Commandant'?' commandant-card':'';return `<div class="leader-specimen" id="${l.faction}-${slugify(l.name)}"><p class="leader-review-label screen-only"><strong>${esc(l.name)}</strong><span>${esc(l.note)}</span></p><article class="gauntlet-card faction-component-card leader-card ${esc(l.faction)}-card${extra}" data-faction="${esc(l.faction)}" data-art-max="1.86" data-art-min="1.34" data-title-min="10" aria-label="${esc(l.name)} ${esc(l.factionLabel)} Leader card"><div class="card-interior"><header class="card-heading"><h3 class="card-title">${esc(l.name)}</h3><div class="leader-faction-line"><span class="leader-faction-emblem" aria-hidden="true"></span><span>${esc(l.factionLabel)}</span></div></header><figure class="card-art has-image"><img src="${esc(l.image)}" alt="Portrait of the ${esc(l.name)}" /></figure><div class="card-rules">${l.sections.map(([label,text,cost])=>`<section class="leader-rule-section"><h4>${esc(label)}${cost?`<span>${esc(cost)}</span>`:''}</h4><p>${esc(text)}</p></section>`).join('')}</div><footer class="card-footer"><span>${esc(l.factionLabel)}</span><span>Leader</span><span>v0.6.3</span></footer></div></article></div>`}
  function renderLeaders(){const root=document.querySelector('#leaderReviewSections');if(!root)return;root.innerHTML=FACTIONS.filter(([id])=>id!=='neutral').map(([f,label])=>{const ls=LEADERS.filter(l=>l.faction===f);return `<section class="review-faction-block" id="leaders-${f}" aria-labelledby="leaders-${f}-title"><div class="review-faction-heading screen-only"><h3 id="leaders-${f}-title">${esc(label)}</h3><span>${ls.length} Leaders</span></div><div class="leader-review-grid">${ls.map(leaderCard).join('')}</div></section>`}).join('')}
  async function renderPlayable(){const root=document.querySelector('#playableReviewSections');if(!root)return;try{const response=await fetch(CANONICAL_SOURCE,{cache:'no-cache'});if(!response.ok)throw new Error(`HTTP ${response.status}`);const canonical=await response.json();const cards=canonical.cards||[];document.querySelectorAll('[data-playable-count]').forEach(n=>n.textContent=String(cards.length));root.innerHTML=FACTIONS.map(([f,label])=>{const list=cards.filter(c=>slugify(c.allegiance)===f).sort((a,b)=>a.name.localeCompare(b.name));if(!list.length)return '';return `<section class="review-faction-block" id="playable-${f}" aria-labelledby="playable-${f}-title"><div class="review-faction-heading screen-only"><h3 id="playable-${f}-title">${esc(label)}</h3><span>${list.length} cards</span></div><div class="full-card-review-grid">${list.map(c=>`<div class="specimen-column"><p class="review-card-label screen-only"><strong title="${esc(c.name)}">${esc(c.name)}</strong><span>Value ${Number(c.cost)}</span></p><iframe class="full-card-review-frame" loading="lazy" src="card-review-render.html?fit=production&amp;card=${encodeURIComponent(c.id)}" title="${esc(c.name)} v0.6.3 production render"></iframe></div>`).join('')}</div></section>`}).join('')}catch(error){root.innerHTML=`<p class="review-note">Unable to load the v0.6.3 canonical card catalog: ${esc(error.message)}</p>`;console.error(error)}}
  renderLeaders();renderPlayable();
})();
