const VERSION = "v0.6.3-candidate";
const state={data:null,search:"",allegiance:"all",cost:"all"};const $=id=>document.getElementById(id);
init().catch(error=>{$("status").innerHTML=`<strong class="status-bad">Candidate load failed.</strong><p>${escapeHtml(error.message)}</p>`;});
async function init(){state.data=await fetch("../data/Gauntlet_v0.6.3_Canonical_Data_Candidate.json",{cache:"no-store"}).then(assertJson);validate(state.data);$("status").innerHTML=`<strong class="status-good">v0.6.3 development candidate</strong><p>${state.data.cards.length} cards · ${state.data.territories.length} Territories · ${state.data.proposals.length} Proposals</p>`;$("cardCount").textContent=state.data.cards.length;$("cardAllegiance").append(...Object.keys(state.data.card_pool_summary).map(name=>option(name,name)));$("cardSearch").addEventListener("input",()=>{state.search=$("cardSearch").value.toLowerCase().trim();renderCards();});$("cardAllegiance").addEventListener("change",()=>{state.allegiance=$("cardAllegiance").value;renderCards();});$("cardCost").addEventListener("change",()=>{state.cost=$("cardCost").value;renderCards();});renderCards();renderTerritories();renderProposals();}
async function assertJson(r){if(!r.ok)throw new Error(`Candidate data returned ${r.status}`);return r.json();}
function validate(d){if(d?.version!==VERSION)throw new Error(`Expected ${VERSION}, received ${d?.version??"unknown"}.`);if(d.cards?.length!==128)throw new Error("Expected 128 cards.");if(d.territories?.length!==25)throw new Error("Expected 25 Territories.");if(d.battlefield?.last_stand?.final_territory_capture_required!==false)throw new Error("Stale Last Stand data.");if(d.setup?.sequence?.[0]!=="prepare_faction_components")throw new Error("Stale setup data.");}
function renderCards(){const cards=state.data.cards.filter(c=>{if(state.allegiance!=="all"&&c.allegiance!==state.allegiance)return false;if(state.cost!=="all"&&String(c.cost)!==state.cost)return false;const h=`${c.name} ${c.allegiance} ${c.trait??""} ${(c.effects??[]).map(e=>`${e.label} ${e.text}`).join(" ")}`.toLowerCase();return !state.search||h.includes(state.search);});const host=$("cardEntries");host.replaceChildren();for(const c of cards){const a=document.createElement("article");a.className="panel reference-entry";a.innerHTML=`<p class="eyebrow">${escapeHtml(c.allegiance)} · value ${c.cost}${c.trait?` · ${escapeHtml(c.trait)}`:""}${c.unique?" · Unique":""}</p><h2>${escapeHtml(c.name)}</h2>${(c.effects??[]).map(e=>`<div class="mode"><strong>${escapeHtml(e.label)}</strong>${formatText(e.text)}</div>`).join("")}`;host.append(a);}}
function renderTerritories(){const host=$("territoryEntries");host.replaceChildren();for(const t of state.data.territories){const a=document.createElement("article");a.className="card";a.innerHTML=`<p class="eyebrow">${t.arena?"Arena":"Territory"} · ${t.number}</p><h3>${escapeHtml(t.name)}</h3><p>${formatText(t.text)}</p>`;host.append(a);}}
function renderProposals(){const host=$("proposalEntries");host.replaceChildren();for(const p of state.data.proposals){const a=document.createElement("article");a.className="card";a.innerHTML=`<p class="eyebrow">Stake ${p.stake}</p><h3>${escapeHtml(p.name)}</h3><p><strong>Requirement:</strong> ${escapeHtml(p.requirement)}</p><div class="mode"><strong>Accepted</strong>${formatText(p.accepted)}</div><div class="mode"><strong>Refused</strong>${formatText(p.refused)}</div>`;host.append(a);}}
function option(v,l){const n=document.createElement("option");n.value=v;n.textContent=l;return n;}function formatText(v){return escapeHtml(v).replaceAll("\n","<br>");}function escapeHtml(v){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");}
