name = "gauntlet-public-media"
main = "src/index.js"
compatibility_date = "2026-08-24"
workers_dev = false

routes = [
  "gauntlet.run/images/media/*",
  "gauntlet.run/tts/v0.7.0/*"
]

[assets]
directory = "./public"
binding = "ASSETS"
run_worker_first = true
